version: '3'

services:
  web:
    build: .
    ports:
      - "${FASTAPI_PORT}:8000"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "${REDIS_PORT}:6379"